<?php

namespace mainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsContentRepository extends EntityRepository
{
}
